steps:
- name: node:20
  entrypoint: npm
  args: ["install"]
- name: node:20
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - HOST=${_HOST}'
    - PORT=${_PORT}'
    - ACCESS_TOKEN_AGE==${_ACCESS_TOKEN_AGE}'
    - ACCESS_TOKEN_KEY==${_ACCESS_TOKEN_KEY}'
    - REFRESH_TOKEN_KEY==${_REFRESH_TOKEN_KEY}'
    
- name: node:20
  entrypoint: npm
  args: ["run", "start"]

- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
